### ISSUE TITLE
[composer|Packagist] last version stuck at 1.2.4

### ISSUE THREAD

**Issue by WedgeSama** [formapro/JsFormValidatorBundle#108]
[Packagist](https://packagist.org/packages/fp/jsformvalidator-bundle) has not been updated. The lastest version available is `1.2.4` (except `dev-master`).

So `1.2.5`, `1.3.0` and `1.4.0` cant be use by composer.

Releated to #107

**Comment by 66Ton99** [comment]
Fixed!
Thanks.
