### ISSUE TITLE
validation for ajax form sending

### ISSUE THREAD

**Issue by vvboyko92** [formapro/JsFormValidatorBundle#117]
I had a problem, when was trying to make comments functionality. When i was trying to submit and send form via ajax my page was reloading, because of js submitting form by your js code. If i am wrong, please correct me.

**Comment by 66Ton99** [comment]
Pleas read this #58

**Comment by vvboyko92** [comment]
Thank you! Sorry about this stupid question. For some reason i didn't find this before

**Comment by 66Ton99** [comment]
No problem. I need add this to the documentation.
