### ISSUE TITLE
Is it possible to use the bundle when Symfony Forms are a stand-alone component?

### ISSUE THREAD

**Issue by sasha-myaffiliates** [formapro/JsFormValidatorBundle#130]
Hi,

I'm using Symfony Forms as a stand-alone component and not using routes.
Is it possible to use the bundle in such scenario?

Thanks,
Sasha

**Comment by 66Ton99** [comment]
I think - YES.
All you need to resolve thees dependencies:
php>=5.5.9
symfony/form: "^2.7|^3.0",
symfony/validator: "^2.7|^3.0",
symfony/assetic-bundle: ">=2.5"

And even if other packages depends on some core Symfony Bundles they will be in vendor folder and you should not use them

**Comment by sasha-myaffiliates** [comment]
Thank you @66Ton99 I will give it a go.
My concern was if not using routes is a blocker.

**Comment by 66Ton99** [comment]
@sasha-myaffiliates Are you able to do it?

**Comment by sasha-myaffiliates** [comment]
Hi @66Ton99, I didn't have a chance to get around to it yet, I will be on it early next week. I'll provide the feedback here.

**Comment by sasha-myaffiliates** [comment]
We're not implementing this feature for now, so I didn't have a chance to get around to it.
Closing the issue.
