### ISSUE TITLE
Webpack/encore support

### ISSUE THREAD

**Issue by danaki** [formapro/JsFormValidatorBundle#134]
Hi, I'm using symfony 3.3 without Assetic. 
```
{{ include('FpJsFormValidatorBundle::javascripts.html.twig') }}
```

doesn't work because there're no "javascripts" twig tag defined. Is it possible to update documentation for Encore users?

https://symfony.com/blog/introducing-webpack-encore-for-asset-management

**Comment by 66Ton99** [comment]
PR is welcome.

**Comment by benr77** [comment]
@danaki Did you get anywhere with this? I am now facing the same issue.

**Comment by danaki** [comment]
@benr77 No, my project was cancelled.

**Comment by boubbin** [comment]
I ended up using assetic for this

**Comment by pesektomas** [comment]
Hello guys, I think so new version (^1.6) work with webpack encore. So this issue can be closed.
