### ISSUE TITLE
Compatible with Symfony 4?

### ISSUE THREAD

**Issue by gvojtko** [formapro/JsFormValidatorBundle#149]
I looking for this bundle which are compatible with Symfony 4. Any idea?

**Comment by 66Ton99** [comment]
Need to update this bundle to work with Synfony 4 and I do not think it would be hard for some one who have experience on SF4 bundles.

Unfortunately I do not work on Symfony now, so MR are welcome.

**Comment by pesektomas** [comment]
Hello @66Ton99. Could I ask you for your opinion on my PR #150? It is very simple way and I welcome your points.

**Comment by 66Ton99** [comment]
Meregd https://github.com/formapro/JsFormValidatorBundle/pull/150
