### ISSUE TITLE
Update packagist

### ISSUE THREAD

**Issue by pesektomas** [formapro/JsFormValidatorBundle#154]
Hello @66Ton99,

Would it be possible to update packagist? I don't see the latest changes in dev-master and I don't know how the updates are set.

Thank you very much.

**Comment by 66Ton99** [comment]
It https://packagist.org/packages/fp/jsformvalidator-bundle should be updated in few hours.

**Comment by pesektomas** [comment]
Perfect, I see it now. Thank you!
