### ISSUE TITLE
Release of 1.6.0 is it possible?

### ISSUE THREAD

**Issue by grossmannmartin** [formapro/JsFormValidatorBundle#159]
Is it possible to release the version 1.6.0 as a non-dev version (tagged)?

> When the bundle is used with Symfony 4.*, the recommended version is 1.6.x-dev.

When `fp/jsformvalidator-bundle` is not a root dependency, composer refuses to install.
eg.
```
# library/composer.json
"name": "vendor/library",
"require": {
    "fp/jsformvalidator-bundle": "1.6.x-dev"
} 

# project/composer.json
"require": {
    "vendor/library": "1.1.1"
} 
```

composer install of project from `project/composer.json` fails with 
```
vendor/library 1.1.1 requires fp/jsformvalidator-bundle 1.6.x-dev -> satisfiable by fp/jsformvalidator-bundle[1.6.x-dev] but these conflict with your requirements or minimum-stability.
```

I believe the 1.6 branch [proven itself](https://github.com/shopsys/shopsys/blob/master/composer.json#L90) to be worthy of release.

**Comment by 66Ton99** [comment]
Done
