### ISSUE TITLE
Difference in 'validation_groups' inheritance to server side component

### ISSUE THREAD

**Issue by hanneskaeufler** [formapro/JsFormValidatorBundle#30]
There is a difference in how the bundle validation models inherit the `validation_groups` option.

Again, considering a form like:

```
- form (validation_groups: Foo, Bar)
    - step1: (type: form)
        - tags: (type: collection, MyTagType)
            - name: (constraints: NotBlank(validation_group: Bar))
```

The symfony form component validates the NotBlank constraint when I submit with `Foo` and `Bar` groups. The js component doesn´t.

If I go ahead and do

```
// MyTagType.php
public function setDefaultOptions(OptionsResolverInterface $resolver)
{
    $resolver->setDefaults([
        'validation_groups' => 'Bar',
    ]);
}
```

the js component also picks up on the constraints.

This should maybe be made consistent? Granted this is not your average form.
And by explicitly setting the `validation_groups` on the MyTagType I can make it work.

**Comment by 66Ton99** [comment]
@hanneskaeufler Did you solve it?

**Comment by hanneskaeufler** [comment]
I worked around the difference by hardcoding the validation group in the `setDefaultOptions` of the child type. Not ideal but works for me for now.

```
// MyTagType.php
public function setDefaultOptions(OptionsResolverInterface $resolver)
{
    $resolver->setDefaults([
        'validation_groups' => 'Bar',
    ]);
}
```
