### ISSUE TITLE
Form items cannot validate if display:hidden

### ISSUE THREAD

**Issue by scottgutman** [formapro/JsFormValidatorBundle#63]
Thank you for this bundle, it is a help!

My form is split into 2 div's. Only one of the divs are visible at a time.

The validator has an error when it processes a hidden field: 
`An invalid form control with name='scs_intakebundle_intake[email]' is not focusable.`

Could you suggest a way for me to validate those items?

**Comment by 66Ton99** [comment]
It would be done with another big task #75
