### ISSUE TITLE
Email validation fails for new Top Level Domains

### ISSUE THREAD

**Issue by abienvenu** [formapro/JsFormValidatorBundle#74]
Email validation fails for "me@mydomain.paris", while this email is valid.

Many new top level domains have been released in 2014, and more to come in 2015. I do not think we can maintain a list of all possible domains in Resources/public/js/constraints/Email.js.

**Comment by 66Ton99** [comment]
Yes, it should be done like here https://github.com/symfony/Validator/blob/b39e2b8853c9080d21d032fe695c40fd6d73fc03/Constraints/EmailValidator.php#L84

**Comment by 66Ton99** [comment]
@abienvenu please take a look at #124
