### ISSUE TITLE
Question: how to delay the submit event and run code when valid?

### ISSUE THREAD

**Issue by richardvenneman** [formapro/JsFormValidatorBundle#76]
We need to run some code when a form is valid (showing an element in the DOM). The strategy is to stop the form submit event in a listener when the form is valid, insert the element in the DOM or update styles, remove the listener and resubmit the form.

If I understand correctly from reading this function, the form is automatically submitted when the form `isValid()`: https://github.com/formapro/JsFormValidatorBundle/blob/master/Resources/public/js/fp_js_validator.js#L260.

jsFormValidator is initialised like this:

``` javascript
$(function(){
  $('#bookingpage form').jsFormValidator({
    onValidate: function(errors, event) {}
  });
});
```

Unfortunately the form submit cannot be stopped from executing with code like this:

``` javascript
$('#bookingpage form').on('submit', function (e) {
  e.preventDefault();
  e.stopPropagation();
  // Or
  return false;
});
```

How can we ensure the form is not submitted when it is valid?

**Comment by 66Ton99** [comment]
Look here #58
