### ISSUE TITLE
Symfony 2.8 compatibility

### ISSUE THREAD

**Issue by FredoVelcro** [formapro/JsFormValidatorBundle#92]
Hello,

Can you update to support Symfony 2.8 branch ?
Thank you ! ;)

**Comment by 66Ton99** [comment]
PR is welcome!

**Comment by wojtas** [comment]
@66Ton99 I could make a PR, I need to use this bundle badly. Right now I'm working on that. If it turns out ok, I'll submit a PR.

**Comment by 66Ton99** [comment]
@wojtas I would be perfect! But do not forget about tests.

**Comment by titolendable** [comment]
Any developments @wojtas ?

**Comment by 66Ton99** [comment]
It will be fixed in new branch 1.3

**Comment by 66Ton99** [comment]
It was fixed in #106
